name: Daily News

on:
  workflow_dispatch:
  schedule:
#    - cron: '0 21 * * *'  # JST 06:00
    - cron: '*/5 * * * *'  # JST 06:00

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run bot
        run: python main.py
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
